name: Publish Docker image

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - magistra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Show Buildx info
        run: |
          echo Name: ${{ steps.buildx.outputs.name }}
          echo Platforms: ${{ steps.buildx.outputs.platforms }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Calc tag
        run: |
          TAG=${GITHUB_REF}
          if [ -z "${TAG}" ]; then
            TAG="${GITHUB_SHA}"
          fi
          echo "::set-output name::${TAG}"
        id: calc_tag
      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: ${{ github.repository_owner }}/certbot-with-dns_valuedomain
          no-cache: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: |
            latest
            ${{ steps.calc_tag.outputs.name }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
